import type { FastifyInstance } from 'fastify';
import { sql } from 'drizzle-orm';
import { db } from '../db';
import { verifyToken } from '../middleware/auth.middleware';

export async function messagesRoutes(app: FastifyInstance){
 app.get('/messages/notes',{preHandler:verifyToken},async(request,reply)=>{
  const me=(request.user as {id:string}).id;
  void db.execute(sql`UPDATE users SET last_active_at=now() WHERE id=${me} AND (last_active_at IS NULL OR last_active_at < now() - interval '60 seconds')`).then(() => {}, () => {});
  const rows=await db.execute(sql`SELECT id,content,created_at,sender_id,receiver_id FROM messages WHERE (sender_id=${me} AND receiver_id=${other.id}) OR (sender_id=${other.id} AND receiver_id=${me}) ORDER BY created_at DESC LIMIT 60`);return {user:{id:other.id,username:other.username,displayName:other.display_name,avatarUrl:other.avatar_url,verifiedAt:other.verified_at,supporterNumber:other.supporter_number,supporterExpiresAt:other.supporter_expires_at,isFounder:Boolean(other.is_founder)},messages:rows.rows.reverse().map((r:any)=>({id:r.id,content:r.content,createdAt:r.created_at,senderId:r.sender_id,receiverId:r.receiver_id}))};});
 app.post('/messages/:username',{preHandler:verifyToken},async(request,reply)=>{const me=(request.user as {id:string}).id;void db.execute(sql`UPDATE users SET last_active_at=now() WHERE id=${me} AND (last_active_at IS NULL OR last_active_at < now() - interval '60 seconds')`).then(() => {}, () => {});const {username}=request.params as {username:string};const body=request.body as {content?:string};const content=body.content?.trim();if(!content)return reply.status(400).send({error:'VALIDATION_ERROR'});const u=await db.execute(sql`SELECT id FROM users WHERE lower(username)=lower(${username}) LIMIT 1`);const other=(u.rows[0] as any);if(!other)return reply.status(404).send({error:'USER_NOT_FOUND'});if(other.id===me)return reply.status(400).send({error:'CANNOT_MESSAGE_SELF'});const blocked=await db.execute(sql`SELECT 1 FROM blocks WHERE (blocker_id=${me} AND blocked_id=${other.id}) OR (blocker_id=${other.id} AND blocked_id=${me}) LIMIT 1`);if(blocked.rows[0])return reply.status(403).send({error:'USER_BLOCKED'});const result=await db.execute(sql`INSERT INTO messages(sender_id,receiver_id,content) VALUES(${me},${other.id},${content}) RETURNING id,content,created_at,sender_id,receiver_id`); const actor=await db.execute(sql`SELECT username,display_name FROM users WHERE id=${me} LIMIT 1`); const a:any=actor.rows[0]; await (app as any).notifyUser(other.id,'message','رسالة جديدة',`@${a?.username||"مستخدم"} أرسل لك رسالة`,me,{actorId:me,url:'/messages?username='+encodeURIComponent(a?.username||'')}); return reply.status(201).send({message:result.rows[0]});});
}
