import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { loginUser, API_URL, startSocialLogin } from '../lib/api';
import { useAuth } from '../context/AuthContext';

export default function LoginPage(){
 const [identifier,setIdentifier]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(false),[suspendedToken,setSuspendedToken]=useState(''),[appealReason,setAppealReason]=useState(''),[appealSent,setAppealSent]=useState(false);
 const {login}=useAuth();const navigate=useNavigate();
 const submit=async(e:React.FormEvent)=>{e.preventDefault();setError('');setLoading(true);try{const data=await loginUser({identifier:identifier.trim(),password});if(data.user?.moderationStatus==='suspended'){setSuspendedToken(data.token);setError('هذا الحساب موقوف بسبب مخالفات المحتوى. يمكنك تقديم استئناف.');return}login(data.user,data.token);navigate('/')}catch(err:any){setError(err.message==='INVALID_CREDENTIALS'?'البيانات غلط، حاول مرة ثانية':'حدث خطأ، حاول مرة ثانية')}finally{setLoading(false)}};
 const social=(p:'facebook'|'twitter')=>{try{startSocialLogin(p)}catch(err:any){setError(err.message==='SOCIAL_LOGIN_NOT_CONFIGURED'?'تسجيل الدخول الاجتماعي غير مفعّل بعد.':'تعذر بدء تسجيل الدخول')}};
 return <main className="auth-page" dir="rtl"><section className="auth-card"><div className="auth-brand">دجلة</div><h1>تسجيل الدخول</h1><p className="auth-subtitle">سجّل دخولك للمتابعة إلى دجلة.</p><form onSubmit={submit}><label>البريد أو اسم المستخدم أو الهاتف<input value={identifier} onChange={e=>setIdentifier(e.target.value)} placeholder="البريد / @username / الهاتف" required autoComplete="username"/></label><label>كلمة المرور<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required autoComplete="current-password"/></label>{error&&<p className="auth-error">{error}</p>}<button className="auth-primary" disabled={loading}>{loading?'جاري الدخول...':'تسجيل الدخول'}</button></form><div className="auth-divider"><span>أو</span></div><button className="auth-social facebook" type="button" onClick={()=>social('facebook')}>الدخول عبر فيسبوك</button><button className="auth-social twitter" type="button" onClick={()=>social('twitter')}>الدخول عبر X / تويتر</button><button className="auth-link" type="button" onClick={()=>navigate('/forgot-password')}>نسيت كلمة المرور؟</button><p className="auth-switch">ما عندك حساب؟ <button type="button" onClick={()=>navigate('/register')}>إنشاء حساب جديد</button></p>{suspendedToken&&<div className="auth-appeal"><strong>طلب استئناف</strong><textarea value={appealReason} onChange={e=>setAppealReason(e.target.value)} placeholder="اكتب سبب طلب الاستئناف..." maxLength={2000}/><button type="button" disabled={!appealReason.trim()||appealSent} onClick={async()=>{try{const r=await fetch(API_URL+'/moderation/appeal',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+suspendedToken},body:JSON.stringify({reason:appealReason.trim()})});if(!r.ok)throw new Error();setAppealSent(true)}catch{setError('تعذر إرسال الاستئناف. حاول مرة ثانية.')}}}>{appealSent?'تم إرسال الاستئناف':'إرسال الاستئناف'}</button></div>}</section></main>
}