import { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { exchangeOAuthToken, linkSocialAccount } from '../lib/api';
import { useAuth } from '../context/AuthContext';

export default function OAuthCallbackPage(){
 const navigate=useNavigate();const {login,token:currentToken}=useAuth();const [token,setToken]=useState('');const [provider,setProvider]=useState<'facebook'|'twitter'>('facebook');const [username,setUsername]=useState('');const [phone,setPhone]=useState('');const [needsProfile,setNeedsProfile]=useState(false);const [error,setError]=useState('');const [loading,setLoading]=useState(true);
 const exchange=async(t:string,p:'facebook'|'twitter',u?:string,ph?:string,mode:'login'|'link'='login')=>{try{if(mode==='link'){if(!currentToken)throw new Error('AUTH_REQUIRED');await linkSocialAccount(currentToken,t,p);navigate('/profile/settings?linked=1',{replace:true});return}const data=await exchangeOAuthToken({accessToken:t,provider:p,username:u,phone:ph});if(data.needsProfile){setNeedsProfile(true);setLoading(false);return}login(data.user,data.token);navigate('/',{replace:true})}catch(err:any){setError(err.code==='USERNAME_TAKEN'?'اسم المستخدم مستخدم مسبقاً.':err.code==='PHONE_TAKEN'?'رقم الهاتف مستخدم مسبقاً.':err.code==='OAUTH_EMAIL_REQUIRED'?'مزود الحساب لم يُرجع بريدًا إلكترونيًا. فعّل صلاحية البريد في إعدادات المزود.':'تعذر إكمال تسجيل الدخول الاجتماعي.');setLoading(false)}};
 useEffect(()=>{const hash=new URLSearchParams(window.location.hash.replace(/^#/,''));const t=hash.get('access_token');const e=hash.get('error_description');if(!t){setError(e||'فشل تسجيل الدخول الاجتماعي');setLoading(false);return}setToken(t);const params=new URLSearchParams(window.location.search);const p=(params.get('provider')||'facebook')==='twitter'?'twitter':'facebook';const mode=params.get('mode')==='link'?'link':'login';setProvider(p);window.history.replaceState({},document.title,'/auth/callback');void exchange(t,p,undefined,undefined,mode)},[]);
 if(needsProfile)return <main className="auth-page" dir="rtl"><section className="auth-card"><div className="auth-brand">دجلة</div><h1>أكمل إنشاء حسابك</h1><p className="auth-subtitle">اسم المستخدم إجباري ورقم الهاتف اختياري.</p><label>اسم المستخدم<input value={username} onChange={e=>setUsername(e.target.value.toLowerCase().replace(/[^a-z0-9_.]/g,'').slice(0,30))} required minLength={2} maxLength={30}/></label><label>رقم الهاتف <span>(اختياري)</span><input type="tel" value={phone} onChange={e=>setPhone(e.target.value)}/></label>{error&&<p className="auth-error">{error}</p>}<button className="auth-primary" disabled={loading||!/^[a-z0-9_.]{2,30}$/.test(username)} onClick={()=>{setLoading(true);setError('');void exchange(token,provider,username,phone.trim()||undefined)}}>إكمال إنشاء الحساب</button></section></main>;
 return <main className="auth-page" dir="rtl"><section className="auth-card"><div className="auth-brand">دجلة</div><h1>{loading?'جاري تسجيل الدخول...':'تعذر تسجيل الدخول'}</h1>{error&&<p className="auth-error">{error}</p>}{!loading&&<button className="auth-primary" onClick={()=>navigate('/login')}>العودة لتسجيل الدخول</button>}</section></main>
}