import { API_URL } from "../lib/api";
import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import type { ReactNode } from "react";
import { useAuth } from "../context/AuthContext";
import VideoPlayer from "../components/VideoPlayer";

type SimplePageProps = { title: string; description: string; icon: ReactNode; };

type ReelPost = { id:string; content:string|null; mediaUrl:string|null; mediaType:string|null; likeCount:number; user:{id:string;username:string;displayName:string|null;avatarUrl:string|null} };
type Story = {id:string;media_url:string;media_type:string;content:string|null;created_at:string;expires_at:string;user_id:string;username:string;display_name:string|null;avatar_url:string|null};

export default function SimplePage({ title, description, icon }: SimplePageProps) {
  const { token, user } = useAuth();
  const isSearch = title === "استكشاف"; const isReels = title === "الريلز"; const isStories = title === "القصص"; const isStory = title === "القصة";
  const [username,setUsername]=useState(""); const [result,setResult]=useState<any>(null); const [loading,setLoading]=useState(false); const [reels,setReels]=useState<ReelPost[]>([]); const [stories,setStories]=useState<Story[]>([]); const [error,setError]=useState(""); const [following,setFollowing]=useState(false);
  const targetUsername=window.location.pathname.startsWith('/stories/')?decodeURIComponent(window.location.pathname.split('/')[2]||''):'';
  useEffect(()=>{if(!isReels||!token)return;let active=true;fetch(`${API_URL}/posts`,{headers:{Authorization:`Bearer ${token}`}}).then(async res=>{const data=await res.json();if(!res.ok)throw new Error();return data;}).then(data=>{if(active)setReels((data.posts??[]).filter((post:ReelPost)=>post.mediaType==="video"));}).catch(()=>{if(active)setError("تعذر تحميل الريلز.");});return()=>{active=false}},[isReels,token]);
  useEffect(()=>{if((!isStories&&!isStory)||!token)return;let active=true;fetch(`${API_URL}/stories`,{headers:{Authorization:`Bearer ${token}`}}).then(async res=>{const data=await res.json();if(!res.ok)throw new Error();return data;}).then(data=>{if(active)setStories(data.stories??[])}).catch(()=>{if(active)setError("تعذر تحميل القصص.")});return()=>{active=false}},[isStories,isStory,token]);
  async function search(event:React.FormEvent){event.preventDefault();const value=username.trim().replace(/^@/,"");if(!value||!token)return;setLoading(true);setError("");setResult(null);try{const res=await fetch(`${API_URL}/auth/search/users/${encodeURIComponent(value)}`,{headers:{Authorization:`Bearer ${token}`}});const data=await res.json();if(!res.ok)throw new Error();setResult({...data.user,isFollowing:data.isFollowing,followerCount:data.followerCount});}catch{setError("ما لكيت حساب بهذا اليوزر.");}finally{setLoading(false);}}
  async function toggleFollow(){if(!result||!token||result.id===user?.id||following)return;setFollowing(true);try{const method=result.isFollowing?"DELETE":"POST";const res=await fetch(`${API_URL}/auth/users/${encodeURIComponent(result.username)}/follow`,{method,headers:{Authorization:`Bearer ${token}`}});const data=await res.json();if(!res.ok)throw new Error();setResult((x:any)=>({...x,isFollowing:data.following,followerCount:Math.max(0,x.followerCount+(data.following?1:-1))}));}catch{setError("تعذر تحديث المتابعة.");}finally{setFollowing(false);}}
  if(isStories)return <main className="feed-container"><section className="stories-card"><div className="section-heading"><h2>القصص</h2><Link to="/create-story">إنشاء قصة</Link></div>{error&&<p className="search-error">{error}</p>}{!error&&!stories.length&&<div className="reels-empty">ماكو قصص منشورة حالياً.</div>}<div className="stories-row">{Array.from(new Map(stories.map(s=>[s.user_id,s])).values()).map(s=><Link to={`/stories/${encodeURIComponent(s.username)}`} className="story" key={s.user_id}><div className="story-ring"><div className="story-image"><img src={s.avatar_url||`https://ui-avatars.com/api/?name=${encodeURIComponent(s.username)}`} alt=""/></div></div><span>{s.display_name||s.username}</span></Link>)}</div></section></main>;
  if(isStory){const story=stories.filter(s=>s.username.toLowerCase()===targetUsername.toLowerCase())[0];return <main className="feed-container"><section className="stories-card"><div className="section-heading"><h2>{story?.display_name||story?.username||targetUsername}</h2><Link to="/stories">القصص</Link></div>{error&&<p className="search-error">{error}</p>}{!error&&!story&&<div className="reels-empty">ماكو قصة فعالة لهذا الحساب حالياً.</div>}{story&&<article className="story-viewer"><div className="story-viewer-media">{story.media_type==="video"?<VideoPlayer src={story.media_url} poster={undefined} />:<img src={story.media_url} alt={story.content||"قصة"}/>}</div>{story.content&&<p>{story.content}</p>}<small>تنتهي القصة: {new Date(story.expires_at).toLocaleString("ar-IQ")}</small></article>}</section></main>}
  if(isReels)return <main className="feed-container"><div className="reels-page"><div className="reels-title"><span>ريلز</span><small>فيديوهات قصيرة من المنشورات</small></div>{error&&<p className="search-error">{error}</p>}{!error&&reels.length===0&&<div className="reels-empty">ماكو ريلز منشورة حالياً.</div>}<section className="reels-list">{reels.map(post=><article className="reel-card" key={post.id}><Link to={`/u/${encodeURIComponent(post.user.username)}`} className="reel-user"><img src={post.user.avatarUrl||`https://ui-avatars.com/api/?name=${encodeURIComponent(post.user.username)}&background=random`} alt=""/><div><strong>{post.user.displayName||post.user.username}</strong><span>@{post.user.username}</span></div></Link><Link to={`/post/${post.id}`} className="reel-video-wrap"><VideoPlayer src={post.mediaUrl||undefined} poster={undefined} /></Link>{post.content&&<p>{post.content}</p>}<div className="reel-meta">♡ {post.likeCount.toLocaleString("ar-IQ")} إعجاب</div></article>)}</section></div></main>;
  return <main className="feed-container"><section className="stories-card" style={{minHeight:420}}>{isSearch?<div className="account-search"><h1>البحث عن حساب</h1><p>البحث يكون باليوزر فقط.</p><form onSubmit={search} className="account-search-form"><input value={username} onChange={e=>setUsername(e.target.value)} placeholder="@username" autoComplete="off"/><button type="submit" disabled={loading||!username.trim()}>{loading?"جاري البحث...":"بحث"}</button></form>{error&&<p className="search-error">{error}</p>}{result&&<div className="search-result"><img src={result.avatarUrl||`https://ui-avatars.com/api/?name=${encodeURIComponent(result.username)}&background=random`} alt={result.username}/><div><strong>{result.displayName||result.username}</strong><span>@{result.username} · {result.followerCount} متابع</span></div><div className="search-actions"><Link to={`/u/${encodeURIComponent(result.username)}`}>عرض الحساب</Link>{result.id!==user?.id&&<button type="button" onClick={()=>void toggleFollow()} disabled={following}>{result.isFollowing?"إلغاء المتابعة":"متابعة"}</button>}</div></div>}</div>:<div style={{textAlign:"center",padding:30}}><div style={{marginBottom:20}}>{icon}</div><h1>{title}</h1><p style={{color:"#777",marginTop:10}}>{description}</p></div>}</section></main>;
}
